<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Livewire\Admin\BrandComponent;
use App\Http\Livewire\Admin\CreateProduct;
use App\Http\Livewire\Admin\DepartmentComponent;
use App\Http\Livewire\Admin\EditProduct;
use App\Http\Livewire\Admin\ShowCategory;
use App\Http\Livewire\Admin\ShowCity;
use App\Http\Livewire\Admin\ShowDepartment;
use App\Http\Livewire\Admin\ShowProducts;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Admin\Productos2;
use App\Http\Livewire\Admin\Patata;
use App\Http\Livewire\Admin\Patata2;
use App\Http\Livewire\Admin\Patata3;
use App\Http\Livewire\Admin\Patata4;
use App\Http\Livewire\Admin\Dormir;
use App\Http\Livewire\Admin\Usuarios;
use App\Http\Livewire\Admin\Papelera;
use App\Http\Livewire\Admin\Link;
use App\Http\Livewire\Admin\Zelda;
use App\Http\Livewire\Admin\Categorias2;
use App\Http\Livewire\Admin\John;
use App\Http\Livewire\Admin\Nombre;
use App\Http\Livewire\Admin\Demon;
use App\Http\Livewire\Admin\Ganon;
use App\Http\Livewire\Admin\Rick;
use App\Http\Livewire\Admin\Examen;


Route::get('/', ShowProducts::class)->name('admin.index');
Route::get('productos2', Productos2::class)->name('admin.productos2');
Route::get('patata', Patata::class)->name('admin.patata');
Route::get('patata2', Patata2::class)->name('admin.patata2');
Route::get('patata3', Patata3::class)->name('admin.patata3');
Route::get('patata4', Patata4::class)->name('admin.patata4');
Route::get('dormir', Dormir::class)->name('admin.dormir');
Route::get('usuarios', Usuarios::class)->name('admin.usuarios');
Route::get('papelera', Papelera::class)->name('admin.papelera');
Route::get('link', Link::class)->name('admin.link');
Route::get('zelda', Zelda::class)->name('admin.zelda');
Route::get('ganon', Ganon::class)->name('admin.ganon');
Route::get('demon', Demon::class)->name('admin.demon');
Route::get('categorias2', Categorias2::class)->name('admin.categorias2');
Route::get('john', John::class)->name('admin.john');
Route::get('nombre', Nombre::class)->name('admin.nombre');
Route::get('rick', Rick::class)->name('admin.rick');
Route::get('examen', Examen::class)->name('admin.examen');
Route::get('products/create', CreateProduct::class)->name('admin.products.create');
Route::get('products/{product}/edit', EditProduct::class)->name('admin.products.edit');
Route::post('product/{product}/files', [ProductController::class, 'files'])->name('admin.products.files');
Route::get('categories', [CategoryController::class, 'index'])->name('admin.categories.index');
Route::get('categories/{category}', ShowCategory::class)->name('admin.categories.show');
Route::get('brands', BrandComponent::class)->name('admin.brands.index');
Route::get('orders', [OrderController::class, 'index'])->name('admin.orders.index');
Route::get('orders/{order}', [OrderController::class, 'show'])->name('admin.orders.show');
Route::get('departments', DepartmentComponent::class)->name('admin.departments.index');
Route::get('departments/{department}', ShowDepartment::class)->name('admin.departments.show');
Route::get('cities/{city}', ShowCity::class)->name('admin.cities.show');
